# -*- coding: utf-8 -*-
"""LAB-5_Task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#LAB-5
#TASK-6

f1 = open('/content/drive/MyDrive/CSE221_Lab-6/Input6.txt','r')
f2 = open('/content/drive/MyDrive/CSE221_Lab-6/Output6.txt','w')

r, c = map(int, f1.readline().split())
print(r,c)

adjMat = []
for i in range(r):
  row = f1.readline()
  adjMat.append(row)
print(adjMat)
maxDiamond = 0


def collectDiamonds(graph, x, y, r, c):
  global diamond
  global visited
  if x>=r or y>=c or x<0 or y<0:
    return
  elif graph[x][y]=="#":
    return
  if graph[x][y]=="D":
    diamond += 1
  visited.append([x,y])   #list of lists[[row,col]]
  if [x+1,y] not in visited:
    collectDiamonds(graph, x+1, y, r, c)
  if [x,y+1] not in visited:
    collectDiamonds(graph, x, y+1, r, c)
  if [x-1,y] not in visited:
    collectDiamonds(graph, x-1, y, r, c)
  if [x,y-1] not in visited:
    collectDiamonds(graph, x, y-1, r, c)

for i in range(r):
  for j in range(c):
    visited = []
    diamond = 0
    collectDiamonds(adjMat, i, j, r, c)
    if diamond > maxDiamond:
      maxDiamond = diamond

#print(visited)
print(maxDiamond,file=f2)

f2.close()