# -*- coding: utf-8 -*-
"""Task3(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-3
#a. Using bubblesort
f1=open('/content/drive/MyDrive/CSE221_Lab-03/Input3.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_Lab-03/Output3_1.txt',mode='w')




queue = []
def enqueue(arr):
  queue.append(arr)
  print(queue,'queue')
  for i in range(len(queue)):
    for j in range(len(queue)-i-1):
      if len(queue[j+1])!=0:
        if int(queue[j][1]) > int(queue[j+1][1]):
          queue[j], queue[j+1] = queue[j+1], queue[j]
    
def seeDoctor():
  if queue == []:
    return -1
  else:
    temp = queue[0]
    queue.pop(0)
    f2.write(temp[0]+'\n')
#   print('in2')

def printQueue():
  read = f1.readline()
  while read!='':
    if read.strip()!= 'see doctor':
      read = read.split()
      enqueue(read)
      #print(read,'r')
    else:
      seeDoctor()
    read = f1.readline()
    #print(read)
printQueue()
f1.close()
f2.close()

#Time complexity O(n^2)