# -*- coding: utf-8 -*-
"""Task1(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-1_2
f1=open('/content/drive/MyDrive/CSE221_Lab-03/Input1_2.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_Lab-03/Output1_2.txt',mode='w')
l1=f1.readline().split()
# list1=[5,9,7,3,1,11,15,13]

list1=[]
for num in l1:
  list1.append(int(num))
print(list1)


def findk(k,arr,low,high):
  #mid=len(list1)//2
  a=partition(list1,low,high)
  if a+1==k:
    return (list1[k-1])
  if k>a+1:
    return findk(k,list1,a+1,high)
    
  if k<a+1:
    return findk(k,list1,low,a-1)

k=5    
print(findk(k,list1,0,len(list1)-1))