# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-3

f1=open('/content/drive/MyDrive/CSE221_lab-04/Input3.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_lab-04/Output3.txt',mode='w')
n1=f1.readline()
l=f1.readline().split( )

list1=[]
for num in l:
  list1.append(int(num))
#list1=[2,7,4,1,5,6,8,3]

def count(arr):
  if len(arr) <= 1:
    return 0
  else:
    mid = len(arr)//2
    l=arr[:mid]
    r=arr[mid:]
    c=count(l)+ count(r)  
  
  
  i=0
  j=0

  while i<len(l) and j<len(r):
    # print(l,'l')
    # print(r,'r')
    if int(l[i])>int(r[j]):
      arr[i+j] = r[j]
      #ascending order sorting
      c+= len(l) - i  
      #remaining elems in l > the current elem(smaller) in r 
      j += 1
    else:
      arr[i+j]=l[i]
      i+=1
  while i<len(l):  #remaining left arr elements
    arr[i+j]=l[i]
    i+=1
  while j<len(r):
    arr[i+j]=r[j]
    j+=1

  return c
    

a=count(list1)
print(a) 
print(str(a),file=f2)
  
f2.close()