# -*- coding: utf-8 -*-
"""Task-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#Task-4
f1=open('/content/drive/MyDrive/CSE221_LAB-7/Input4.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_LAB-7/Output4.txt',mode='w')
l1=f1.readline().split( )
n=int(l1[0])           #idx= 0,1,2,3,4,5,6
                       #fib= 0,1,1,2,3,5,8

num=n+1 #50th stair=index no 51
fib1=[None]*(num+1)
fib1[0]=0
fib1[1]=1
def fib(n):
  if n<=1:
    return n
  elif fib1[n]!=None:
    return fib1[n]
  else:
    val=fib(n-1)+fib(n-2)
    fib1[n]=val
    return val
a=fib(num)
print(a,file=f2)