# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#Task-1
f1=open('/content/drive/MyDrive/CSE221_LAB-7/Input1.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_LAB-7/Output1.txt',mode='w')
n=int(f1.readline())
list1=[]
c=0
end=-1
l=[]
ans=[]
for i in range(n):
  var=f1.readline().split()
  #print(var)
  a=int(var[1]),int(var[0])
  list1+=[a]
list1.sort()
#print(list1)
for i in range(len(list1)):
  #print(list1[i][0])
  if end<=list1[i][1]:
    l.append(list1[i])
    c+=1
    end=list1[i][0]
print(c,file=f2)
for elem in l:
  a=elem[1],elem[0]
  print(a[0], a[1],file=f2)

   

#print(ans)