# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#Task-2
f1=open('/content/drive/MyDrive/CSE221_LAB-7/Input2.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_LAB-7/Output2.txt',mode='w')
l=f1.readline().split()
n=int(l[0])
e=int(l[1])

count = [1]*(n+1)
par = [0]*(n+1)

for i in range(1,n+1):
  par[i] = i

#print(count,'count')

def find(par, i):
  if par[i] == i:
    return i
  else:
    return find(par, par[i])
#print(par,'par')
for i in range(e):
  var=f1.readline().split()
  a=int(var[0])
  b=int(var[1])
  u = find(par, a)
  v = find(par, b)
  if u!=v:
    par[u] = v
    count[v] += count[u]
  print(f'{count[v]}',file=f2)