# -*- coding: utf-8 -*-
"""Task1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-1-part-1

#Solution with O(n^2) time complexity

f1=open('/content/drive/MyDrive/CSE221_Lab-02/Input1.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_Lab-02/Output1_1.txt',mode='w')
var1=f1.readline().split()
n=var1[0]
sum=var1[1]
l1=f1.readline().split()
l2=[]
for i in range(int(n)):
  for j in range(i+1,len(l1)-1):
    if int(l1[i])+int(l1[j])==int(sum):
      l2.append(i+1)
      l2.append(j+1)
#print(l2)
if len(l2)==0:
  print('IMPOSSIBLE',file=f2)
for num in l2:
  print(num,end=" ",file=f2)
f2.close()