# -*- coding: utf-8 -*-
"""Task2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-2(part-2)

#Solution with O(n) time complexity

f1=open('/content/drive/MyDrive/CSE221_Lab-02/Input2.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_Lab-02/Output2_2.txt',mode='w')
n1=f1.readline()
list1=f1.readline().split( )
n2=f1.readline()
list2=f1.readline().split( )
ans=[]
def merge(l1,l2):
  i=0
  j=0

  while i<len(l1) and j<len(l2):
    if int(l1[i])<int(l2[j]):
      ans.append(int(l1[i]))
      i+=1
    else:
      ans.append(int(l2[j]))
      j+=1
  while i<len(l1):
    ans.append(int(l1[i]))
    i+=1
  while j<len(l2):
    ans.append(int(l2[j]))
    j+=1
  
merge(list1,list2)
for num in ans:
  print(num,end=" ",file=f2)
  
f2.close()