# -*- coding: utf-8 -*-
"""Task1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-1-part-2

#Solution with O(n) time complexity

f1=open('/content/drive/MyDrive/CSE221_Lab-02/Input1.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_Lab-02/Output1_2.txt',mode='w')
var1=f1.readline().split()
n=var1[0]
sum=int(var1[1])
l1=f1.readline().split()
d1={}
#for k,v in d1.items():
for i in range(int(n)):
  d1.update({i+1:int(l1[i])})
#print(d1)
l2=[]

val_list=list(d1.values())
for k,v in d1.items():
  var=sum-v
  if var in d1.values():
    #print(var)
    l2.append(k)
    l2.append(val_list.index(var)+1)
    break
  
#print(l2)
if len(l2)==0:
  print('IMPOSSIBLE',file=f2)
for num in l2:
  print(num,end=" ",file=f2)
f2.close()