# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-4
f1=open('/content/drive/MyDrive/CSE221_lab-05/Input4_2.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_lab-05/Output4.txt',mode='w')
l1=f1.readline().split( )
n=int(l1[0])
e=int(l1[1])
d= {}
   
for i in range(e): 
  l2=f1.readline().split()
  a=int(l2[0]) 
  b=int(l2[1])
  for i in range(1,n+1):
    if i not in d:
      d[i]=[]
  if a in d:
    d[a].append(b)
  elif a not in d:
    d[a] = [b]
print(d) 

queue=[]
color={}

for u in d.keys():  #v=g.keys
  color[u] = 'W'

def dfs(g,u):    
  color[u]='G'
  for v in g[u]:
    if color[v]=='W':
      dfs(g,v)
    elif color[v]=='G':
      
      print('Yes',file=f2)
    else:
      print('No',file=f2)

  color[u]='B'
  
dfs(d,1)
f2.close()