# -*- coding: utf-8 -*-
"""Task1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-1(a)
f1=open('/content/drive/MyDrive/CSE221_lab-05/Input1A.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_lab-05/Output1A.txt',mode='w')
l1=f1.readline().split( )
n=int(l1[0])
e=int(l1[1])
adj = [[0 for i in range(n+1)] for j in range(n+1)]
#print(adj)
for i in range(e):
  l2=f1.readline().split()
  u=int(l2[0])
  v=int(l2[1])
  w=int(l2[2])
  # print(u,'u')
  # print(v,'v')
  # print(w,'w')
  adj[u][v]=w
#print(adj)
for i in range(n+1):
  for j in range(n+1):
    print(adj[i][j],end=" ", file=f2)
  print("\n", file=f2)