# -*- coding: utf-8 -*-
"""Task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-1(b)
f1=open('/content/drive/MyDrive/CSE221_lab-05/Input1A.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_lab-05/Output1B.txt',mode='w')
l1=f1.readline().split( )
n=int(l1[0])
e=int(l1[1])
d= {}
   
for i in range(e):
  
  l2=f1.readline().split()
  u=int(l2[0])
  v=int(l2[1])
  w=int(l2[2])
  
  for i in range(n+1):
    if i not in d:
      d[i]=[]

  if(u in d):
    d[u].append(str(tuple([v,w])))

  elif u not in d:
    d[u] = [str(tuple(v,w))]
print(d)   
for k,v in d.items():
  print(f'{k}:{" ".join(v)}',file=f2)
  #print(f'{k}:{" ".join(v)}')
f2.close()