# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-3
f1=open('/content/drive/MyDrive/CSE221_lab-05/Input3_3.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_lab-05/Output3.txt',mode='w')
l1=f1.readline().split( )
n=int(l1[0])
e=int(l1[1])
d= {}
   
for i in range(e): 
  l2=f1.readline().split()
  a=int(l2[0]) 
  b=int(l2[1])
  for i in range(1,n+1):
    if i not in d:
      d[i]=[]
  if a in d:
    d[a].append(b)
  elif a not in d:
    d[a] = [b]
print(d) 

queue=[]
color={}
def colourInitializing(g):
  for v in g:  #v=g.keys
    color[v] = 'W'

def DFS(g,s):    
  if color[s]=='W':
    print(s,end=" ",file=f2)
    color[s]='G'
    for v in g[s]:
      DFS(g,v)
  color[s]='B'
colourInitializing(d)
DFS(d,1)
f2.close()