# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""



#Task-2
f1=open('/content/drive/MyDrive/CSE221_lab-05/Input2_2.txt',mode='r')
f2=open('/content/drive/MyDrive/CSE221_lab-05/Output2.txt',mode='w')
l1=f1.readline().split( )
n=int(l1[0])
e=int(l1[1])
d= {}
   
for i in range(e): 
  l2=f1.readline().split()
  a=int(l2[0]) 
  b=int(l2[1])
  for i in range(1,n+1):
    if i not in d:
      d[i]=[]
  if a in d:
    d[a].append(b)
  elif a not in d:
    d[a] = [b]
print(d) 

queue=[]
color={}
def BFS(g,s):
  for v in g:  #v=g.keys
    color[v] = 0
  #print(color) #1,2,3,4 all vertices=0
  color[s]=1
  queue.append(s)

  while queue:
    u=queue.pop(0)
    print(u,end=" ",file=f2)
    for v in g[u]: #g[u]=g.values #v=adj/neighbour
      if color[v]==0:
        color[v]=1
        queue.append(v)   
BFS(d,1)
f2.close()