# -*- coding: utf-8 -*-
"""Task-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#Task-5
f1 = open('/content/drive/MyDrive/CSE221_Lab-01/Input5.txt',mode='r')
f2 = open('/content/drive/MyDrive/CSE221_Lab-01/Output5.txt',mode='w')
num = int(f1.readline().strip())
l1 = []
iteration = 1

for i in range(num):
    l2 = f1.readline().split()
    l1.append([l2[0], l2[4], l2[6], iteration])
    iteration+=1
# print(l1)
# print()
for i in range(len(l1)-1):  #or range(num)
  for j in range(i+1,len(l1)):
    if l1[i][0] > l1[j][0]:
      l1[i], l1[j] = l1[j], l1[i]
# print(l1)
# print()
for i in range(len(l1)-1):
  for j in range(i+1,len(l1)):
    if l1[i][0]== l1[j][0] and l1[i][2] < l1[j][2]:
      l1[i], l1[j] = l1[j], l1[i]
# print(l1)
# print()
for i in range(len(l1)-1):
  for j in range(i+1,len(l1)):
    if l1[i][0]== l1[j][0] and l1[i][2]== l1[j][2] and l1[i][3] > l1[j][3]:
      l1[i], l1[j] = l1[j], l1[i]
# print(l1)
for i in range(num):
    print(f"{l1[i][0]} will departure for {l1[i][1]} at {l1[i][2]}",file=f2)
f1.close()
f2.close()