# -*- coding: utf-8 -*-
"""Task-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#Task-4
import operator
f1 = open('/content/drive/MyDrive/CSE221_Lab-01/Input4.txt',mode='r')
f2 = open('/content/drive/MyDrive/CSE221_Lab-01/Output4.txt',mode='w')
no=f1.readline()
id=f1.readline().split()
num=f1.readline().split()

list1=[]
for i in range(int(no)):
  list1.append([id[i],num[i]])
#print(list1)
for i in range(len(list1)-1):  #till 2nd last index
  for j in range(i+1,len(list1)):
    if list1[i][1] < list1[j][1]:
      list1[i], list1[j] = list1[j], list1[i]
#print(list1)
for i in range(len(list1)-1):  
  for j in range(i+1,len(list1)):
    if list1[i][1]==list1[j][1] and list1[i][0]>list1[j][0]:
      list1[i], list1[j] = list1[j], list1[i]
#print(list1)
for i in range(len(list1)):
  print(f'ID:{list1[i][0]} Mark:{list1[i][1]}',file=f2)
f2.close()