# -*- coding: utf-8 -*-
"""Task-1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#task-1a
inp_file=open('/content/drive/MyDrive/CSE221_Lab-01/Input1a.txt',mode='r')
data= inp_file.readlines()  
#data=['5','10',..]
out_file=open('/content/drive/MyDrive/CSE221_Lab-01/Output1a.txt',mode='w')

for i in range(1,(int(data[0])+1)):
  if int(data[i])%2==0:
    print(f"{int(data[i])} is an Even number",file=out_file)
  else:
    print(f"{int(data[i])} is an Odd number",file=out_file)

out_file.close()