# -*- coding: utf-8 -*-
"""Task-1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11U1Jq-hfafCjyQcQYQmu9Lpy0s8OFYz9
"""

#task-1b

inp_file=open('/content/drive/MyDrive/CSE221_Lab-01/Input1b.txt',mode='r')
data= inp_file.readlines()  
out_file=open('/content/drive/MyDrive/CSE221_Lab-01/Output1b.txt',mode='w')

for i in range(1,(int(data[0])+1)):
  s=data[i].split(" ")
  if s[2]=="+":
    ans=int(s[1])+int(s[3])
    print(f'The result of {int(s[1])} {s[2]} {int(s[3])} is {ans}',file=out_file)
  elif s[2]=="-":
    ans=int(s[1])-int(s[3])
    print(f'The result of {int(s[1])} {s[2]} {int(s[3])} is {ans}',file=out_file)
  elif s[2]=="*":
    ans=int(s[1])*int(s[3])
    print(f'The result of {int(s[1])} {s[2]} {int(s[3])} is {ans}',file=out_file)
  elif s[2]=="/":
    ans=int(s[1])/int(s[3])
    print(f'The result of {int(s[1])} {s[2]} {int(s[3])} is {ans}',file=out_file)
out_file.close()